---
- hosts: all

- name: import common file
  import_playbook: ../static-assignments/common.yml
  tags:
     - always

- name: import loadbalancer file
  import_playbook: ../static-assignments/loadbalancers.yml


- name: import webservers file
  import_playbook: ../static-assignments/webservers.yml

- name: include env-vars file
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
      - always